[package]
name = "ineeng"
version = "1.1.1"
edition = "2021"

[dependencies]
bors = { path = "../bors", default-features = false }

[features]
default = ["std"]
std = ["bors/std"]
alloc = ["bors/std"]

[lib]
doctest = false
bench = false